name: 'Update Package Versions'

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: 'Package to update'
        required: true
      package-version:
        description: 'New package version'
        required: true

permissions:
  contents: write

jobs:
  upgrade-package-version:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.create-branch.outputs.branch-name }}  # Set the branch name as an output

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Setup NodeJS'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Fetch Latest Changes'
        run: |
          git fetch --all
          git checkout master
          git pull origin master

      - name: Install Dependencies
        run: npm install

      - name: Run Package Update Script
        run: |
          node src/upgrade-package.mjs ${{ github.event.inputs.package-name }} ${{ github.event.inputs.package-version }}

      - name: Create Branch for Changes
        id: create-branch
        run: |
          # Generate a branch name dynamically based on timestamp
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-packages-${timestamp}"
          echo "branch-name=${branch_name}" >> $GITHUB_ENV
          echo "::set-output name=branch-name::${branch_name}"

  create-pull-request:
    runs-on: ubuntu-latest
    needs: upgrade-package-version
    with:
      branch: ${{ needs.upgrade-package-version.outputs.branch-name }}  # Use the dynamically set branch name from the previous job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ needs.upgrade-package-version.outputs.branch-name }}  # Use the dynamically set branch name from previous step
          base: master
          title: "chore: Update ${{ github.event.inputs.package-name }} to v${{ github.event.inputs.package-version }}"
          body: |
            This PR updates the package `${{ github.event.inputs.package-name }}` to version `${{ github.event.inputs.package-version }}`.
            - Automated by GitHub Actions 🤖
          labels: dependencies
          assignees: suryac72
